name: Forward AIMET commits to public repo (test)

on:
  workflow_dispatch:

jobs:
  repo-sync:
    if: github.server_url != 'https://github.com'
    runs-on: ubuntu-latest
    env:
      INTERNAL_REPO_DIR: "aimet-repo"
      INTERNAL_SRC_BRANCH: "dev/bhushans/test-branch"
      PUBLIC_DST_BRANCH: "dev/bhushans/test-branch"
    steps:
      - name: Checkout internal repo
        uses: actions/checkout@v4
        with:
          ref: ${{ env.INTERNAL_SRC_BRANCH }}
          path: ${{ env.INTERNAL_REPO_DIR }}
          fetch-depth: 0
      - name: Push to public repository
        run: |
          cd ${INTERNAL_REPO_DIR}
          git remote add public-origin https://${{ secrets.AIMET_CI }}@github.com/quic/aimet.git
          git push public-origin ${{ env.INTERNAL_SRC_BRANCH }}:${{ env.PUBLIC_DST_BRANCH }}

