name: Run Unit and Acceptance tests

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string
        default: aimet-dev
      ver_python:
        required: false
        type: string
        default: "3.10"
      ver_cuda:
        required: false
        type: string
        default: ""
      ver_torch:
        required: false
        type: string
        default: ""
      ver_onnxruntime:
        required: false
        type: string
        default: ""
      pip_index:
        required: false
        type: string
        default: ""
      run_unit_tests:
        required: false
        type: boolean
        default: false
      run_acceptance_tests:
        required: false
        type: boolean
        default: false
      runs_on:
        required: true
        type: string
      include_windows_tests:
        required: false
        type: boolean
        default: false

jobs:
  test_on_linux:
    name: Run AIMET unit and acceptance tests on Ubuntu
    runs-on: ${{ inputs.runs_on }}
    if: inputs.run_unit_tests || inputs.run_acceptance_tests
    env:
      pytest_github_report: true
      pytest_use_zeros: true
    container:
      image: "ubuntu:22.04"
    steps:
      - name: Install dependencies
        run: |
          apt update -qq
          apt install --no-install-recommends -y git curl g++ ca-certificates cmake make
          # ref: https://qwiki.qualcomm.com/it-sec-public/QC_SSL#Machines
          curl -L 'https://pki.qualcomm.com/{qc_root_g2_cert.crt,ssl_v3_cert.crt,ssl_v4_cert.crt}' -o '/usr/local/share/ca-certificates/#1'
          update-ca-certificates
          # Update certificate env variables
          echo "REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
          echo "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt" >> $GITHUB_ENV
          rm -rf download
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: "${{ inputs.env_name }}-wheel"
          path: "downloads"
      - uses: actions/download-artifact@v3
        with:
          name: "${{ inputs.env_name }}-tests"
          path: "downloads"
      - name: Create python virtual environment
        if: ${{ inputs.env_name  != 'onnx-torch-cpu' }}
        uses: ./.github/actions/setup-conda-env
        with:
          ENV_NAME: ${{ inputs.env_name }}
          VER_PYTHON: ${{ inputs.ver_python }}
          VER_CUDA: ${{ inputs.ver_cuda }}
          VER_TORCH: ${{ inputs.ver_torch }}
          VER_ONNXRUNTIME: ${{ inputs.ver_onnxruntime }}
          PIP_INDEX: ${{ matrix.PIP_INDEX }}
      - name: Run pylint
        run: |
          CONDA_PYTHONPATH="./.conda/envs/${{ inputs.env_name }}/lib/python${{ inputs.ver_python }}/site-packages"
          AIMET_PACKAGES=$(find $CONDA_PYTHONPATH -regex ".*/aimet_\(common\|torch\|onnx\)" | tr "\n" " ")

          ./.conda/bin/conda run --live-stream --name "${{ inputs.env_name }}" \
              python3 -m pylint --rcfile=.pylintrc $AIMET_PACKAGES
      - name: Run Unit tests
        if: inputs.run_unit_tests
        run: |
          set -x

          for target in $(find downloads -name "*Test"); do
              chmod +x $target
              # NOTE: Set LD_LIBRARY_PATH for dynamic linking with libpython3.so
              #       since ubuntu:22.04 docker image doesn't have built-in libpython3.so
              LD_LIBRARY_PATH=".conda/envs/${{ inputs.env_name }}/lib" \
                  ./.conda/bin/conda run --live-stream --name "${{ inputs.env_name }}" $target
          done

          PYTEST_TARGETS="./ModelOptimizations/DlQuantization/test"
          PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/common/test"

          if [ "${{ inputs.ver_onnxruntime }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/onnx/test"
          elif [ "${{ inputs.ver_torch }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/torch/test"
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ inputs.ver_cuda }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          ./.conda/bin/conda run --live-stream --name "${{ inputs.env_name }}" python3 -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS
      - name: Run Acceptance tests
        if: inputs.run_acceptance_tests
        run: |
          set -x
          PYTEST_TARGETS=""
          if [ "${{ inputs.ver_onnxruntime }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/onnx"
          elif [ "${{ inputs.ver_torch }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/torch"
              ./.conda/bin/conda run --live-stream --name "${{ inputs.env_name }}" python3 -m pip install wget
              ./.conda/bin/conda run --live-stream --name "${{ inputs.env_name }}" python3 ./NightlyTests/torch/dependencies.py ./NightlyTests/torch/resnet18_eval_scores.csv
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ inputs.ver_cuda }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          ./.conda/bin/conda run --live-stream --name "${{ inputs.env_name }}" python3 -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS

  test_on_windows:
    name: Run AIMET unit and acceptance tests on Windows
    runs-on: [self-hosted, Windows]
    if: inputs.include_windows_tests && inputs.env_name == 'onnx-cpu' && (inputs.run_unit_tests || inputs.run_acceptance_tests)
    steps:
      - uses: actions/checkout@v4

      - name: Redirect temp directories to workspace for automated cleanup
        run: |
          $env:TEMP = "$env:GITHUB_WORKSPACE\temp"
          $env:TMP = "$env:GITHUB_WORKSPACE\temp"

      - name: Download built wheels
        uses: actions/download-artifact@v3
        with:
          name: "onnx-cpu-win-wheel"
          path: "downloads"

      - uses: ./.github/actions/setup-uv-env
        with:
          ENV_NAME: "onnx-cpu"
          VER_PYTHON: "3.10"
          PIP_INDEX: ""
          VER_CUDA: ""

      - name: Run Unit tests
        if: inputs.run_unit_tests
        run: |

          # Activate uv environment
          .\onnx-cpu\Scripts\activate

          # Run tests
          $pytest_args = "not cuda"
          Invoke-Expression "pytest -m `"$pytest_args`" -n 8 .\\ModelOptimizations\\DlQuantization\\test"
          Invoke-Expression "pytest -m `"$pytest_args`" -n 8 .\\TrainingExtensions\\common\\test\\python"
          # TODO: #6211 Move torch to onnx tests out of unit tests
          Invoke-Expression "pytest -m `"$pytest_args`" -n 8 .\\TrainingExtensions\\onnx\\test\\python --ignore .\\TrainingExtensions\\onnx\\test\\python\\test_torch_to_onnx.py"

      - name: Run Acceptance tests
        if: inputs.run_acceptance_tests
        run: |
          # Activate uv environment
          .\onnx-cpu\Scripts\activate

          # Run tests
          $pytest_args = "not cuda"
          Invoke-Expression "pytest -m `"$pytest_args`" .\\NightlyTests\\onnx -n 8"

