name: Run Unit and Acceptance tests

on:
  workflow_call:
    inputs:
      env_name:
        required: false
        type: string
        default: aimet-dev
      ver_python:
        description: "Comma-separated Python versions to test, e.g. '3.10,3.11,3.12'"
        required: false
        type: string
        default: "3.10"
      ver_cuda:
        required: false
        type: string
        default: ""
      ver_torch:
        required: false
        type: string
        default: ""
      ver_onnxruntime:
        required: false
        type: string
        default: ""
      pip_index:
        required: false
        type: string
        default: ""
      run_unit_tests:
        required: false
        type: boolean
        default: false
      run_acceptance_tests:
        required: false
        type: boolean
        default: false
      include_windows_tests:
        required: false
        type: boolean
        default: false

jobs:
  parse_python_versions:
    name: Parse Python versions
    runs-on: ubuntu-latest
    outputs:
      python_versions: ${{ steps.set-matrix.outputs.python_versions }}
    steps:
      - name: Convert comma-separated Python versions to JSON array
        id: set-matrix
        run: |
          # Convert "3.10,3.11,3.12" to JSON array ["3.10","3.11","3.12"]
          versions="${{ inputs.ver_python }}"
          json_array=$(echo "$versions" | tr ',' '\n' | jq -R . | jq -sc .)
          echo "python_versions={\"ver_python\":$json_array}" >> $GITHUB_OUTPUT

  start-runner:
    if: ${{ inputs.run_unit_tests || inputs.run_acceptance_tests }}
    name: Start runner (${{ inputs.env_name }}, Python ${{ matrix.ver_python }})
    needs: [parse_python_versions]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.parse_python_versions.outputs.python_versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/start-gpu-runner
        with:
          runner-id: ${{ inputs.env_name }}-py${{ matrix.ver_python }}-tests-${{ github.run_id }}-${{ github.run_attempt }}
          gpu-request: ${{ inputs.ver_cuda != '' && '1' || '0' }}
          cpu-request: "64"
          docker-image: ${{ inputs.ver_cuda != '' && format('docker-registry.qualcomm.com/library/nvidia/cuda:{0}-cudnn-devel-ubuntu22.04', inputs.ver_cuda) || 'docker-registry.qualcomm.com/library/ubuntu:22.04' }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          pat-token: ${{ secrets.SOURCE_REPO_PAT }}

  test_on_linux:
    name: Run AIMET unit and acceptance tests on Ubuntu (Python ${{ matrix.ver_python }})
    needs: [parse_python_versions, start-runner]
    runs-on: ${{ inputs.env_name }}-py${{ matrix.ver_python }}-tests-${{ github.run_id }}-${{ github.run_attempt }}
    if: ${{ inputs.run_unit_tests || inputs.run_acceptance_tests }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.parse_python_versions.outputs.python_versions) }}
    env:
      pytest_github_report: true
      pytest_use_zeros: true
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y git curl g++ ca-certificates cmake make
          rm -rf download
      - name: Set CUDA_HOME for GPU builds
        if: inputs.ver_cuda != ''
        run: |
          # Set CUDA_HOME for deepspeed and other CUDA-dependent packages
          echo "CUDA_HOME=/usr/local/cuda" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: "${{ inputs.env_name }}-wheel"
          path: "downloads"
      - uses: actions/download-artifact@v3
        if: inputs.ver_onnxruntime != ''
        with:
          name: "${{ inputs.env_name }}-tests"
          path: "downloads"
      # Download both aimet-torch and aimet-onnx wheels for acceptance tests
      # for joint testing of torch and onnx packages in the same environment
      - uses: actions/download-artifact@v3
        if: inputs.run_acceptance_tests
        with:
          name: "torch-${{ inputs.ver_cuda == '' && 'cpu' || 'gpu' }}-wheel"
          path: "downloads"
      - uses: actions/download-artifact@v3
        if: inputs.run_acceptance_tests
        with:
          name: "onnx-${{ inputs.ver_cuda == '' && 'cpu' || 'gpu' }}-wheel"
          path: "downloads"
      - name: Create python virtual environment
        if: ${{ inputs.env_name  != 'onnx-torch-cpu' }}
        uses: ./.github/actions/setup-uv-env
        with:
          ENV_NAME: ${{ inputs.env_name }}
          VER_PYTHON: ${{ matrix.ver_python }}
      - name: Install test dependencies
        shell: bash
        run: |
          . ./${{ inputs.env_name }}/bin/activate

          python3 -m ensurepip --upgrade
          python3 -m pip install uv

          if [[ "${{ inputs.run_acceptance_tests }}" == 'true' ]]; then
            # Install both aimet-torch and aimet-onnx wheels for acceptance tests
            # for joint testing of torch and onnx packages in the same environment
            WHEEL_PATHS=$(find downloads -name "aimet_*.whl")
          elif [[ "${{ inputs.env_name }}" == "torch-cpu" || "${{ inputs.env_name }}" == "torch-gpu" ]]; then
            WHEEL_PATHS=$(find downloads -name "aimet_torch*.whl" | head -n 1)
          elif [[ "${{ inputs.env_name }}" == "onnx-cpu" || "${{ inputs.env_name }}" == "onnx-gpu" ]]; then
            WHEEL_PATHS=$(find downloads -name "aimet_onnx*.whl" | head -n 1)
          fi

          # Install test dependencies
          cu=$(echo "${{ inputs.ver_cuda }}" | awk -F'.' '{print ($1!="")? "cu"$1$2 : "cpu"}')
          for wheel in $WHEEL_PATHS; do
            python3 -m uv pip install "${wheel}[test]" \
                --extra-index-url="https://download.pytorch.org/whl/${cu}" \
                --index-strategy unsafe-best-match
          done
      - name: Run pylint
        # TODO: #6789: Enable pylint for python 3.11 and 3.12
        if: matrix.ver_python == '3.10'
        run: |
          . ./${{ inputs.env_name }}/bin/activate
          UV_PYTHONPATH="./${{ inputs.env_name }}/lib/python${{ matrix.ver_python }}/site-packages"

          # Set LD_LIBRARY_PATH for dynamic linking with libpython3.so
          PYTHON_LIB_PATH=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
          export LD_LIBRARY_PATH="${PYTHON_LIB_PATH}:${LD_LIBRARY_PATH}"

          # Run pylint on aimet-onnx or aimet-torch
          if [ "${{ inputs.ver_onnxruntime }}" != "" ] ; then
              AIMET_ONNX_PATH=$(find $UV_PYTHONPATH -regex ".*/aimet_onnx")
              if [ -z "$AIMET_ONNX_PATH" ]; then
                echo "aimet_onnx package not found in $UV_PYTHONPATH"
              fi
              python -m pylint --rcfile=.pylintrc $AIMET_ONNX_PATH
          elif [ "${{ inputs.ver_torch }}" != "" ] ; then
            AIMET_TORCH_PATH=$(find $UV_PYTHONPATH -regex ".*/aimet_torch")
            if [ -z "$AIMET_TORCH_PATH" ]; then
              echo "aimet_torch package not found in $UV_PYTHONPATH"
            fi
            python -m pylint --rcfile=.pylintrc $AIMET_TORCH_PATH
          fi

      - name: Run Unit tests
        if: inputs.run_unit_tests
        run: |
          set -x
          . ./${{ inputs.env_name }}/bin/activate

          PYTHON_LIB_PATH=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
          export LD_LIBRARY_PATH="${PYTHON_LIB_PATH}:${LD_LIBRARY_PATH}"
          for target in $(find downloads -name "*Test"); do
              chmod +x $target
              $target
          done

          PYTEST_TARGETS="./TrainingExtensions/common/test"

          if [ "${{ inputs.ver_onnxruntime }}" != "" ] ; then
              PYTEST_TARGETS="./ModelOptimizations/DlQuantization/test $PYTEST_TARGETS"
              PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/onnx/test"
          elif [ "${{ inputs.ver_torch }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./TrainingExtensions/torch/test"
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ inputs.ver_cuda }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          python -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS
      - name: Run Acceptance tests
        if: inputs.run_acceptance_tests
        run: |
          set -x
          . ./${{ inputs.env_name }}/bin/activate

          # Set LD_LIBRARY_PATH for dynamic linking with libpython3.so
          PYTHON_LIB_PATH=$(python3 -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
          export LD_LIBRARY_PATH="${PYTHON_LIB_PATH}:${LD_LIBRARY_PATH}"

          PYTEST_TARGETS="./NightlyTests/common"
          if [ "${{ inputs.ver_onnxruntime }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/onnx"
          elif [ "${{ inputs.ver_torch }}" != "" ] ; then
              PYTEST_TARGETS="$PYTEST_TARGETS ./NightlyTests/torch"
              uv pip install wget
              python ./NightlyTests/torch/dependencies.py ./NightlyTests/torch/resnet18_eval_scores.csv
          fi
          PYTEST_ARGS="not blah"
          if [ "${{ inputs.ver_cuda }}" = "" ] ; then
              PYTEST_ARGS="not cuda"
          fi
          python -m pytest -m "$PYTEST_ARGS" $PYTEST_TARGETS

  cleanup-runner:
    if: ${{ always() && (inputs.run_unit_tests || inputs.run_acceptance_tests) }}
    name: Cleanup runner (${{ inputs.env_name }}, Python ${{ matrix.ver_python }})
    needs: [parse_python_versions, start-runner, test_on_linux]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.parse_python_versions.outputs.python_versions) }}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/stop-gpu-runner
        with:
          runner-ids: ${{ inputs.env_name }}-py${{ matrix.ver_python }}-tests-${{ github.run_id }}-${{ github.run_attempt }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          pat-token: ${{ secrets.SOURCE_REPO_PAT }}

  test_on_windows:
    name: Run AIMET unit and acceptance tests on Windows (${{ matrix.arch }})
    runs-on: [self-hosted, Windows, "${{ matrix.arch }}"]
    if: inputs.include_windows_tests && inputs.env_name == 'onnx-cpu' && (inputs.run_unit_tests || inputs.run_acceptance_tests)
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: X64
            python-version: "3.10"
            wheel-arch: x64
          - arch: ARM64
            python-version: "3.12"
            wheel-arch: arm64
    steps:
      - uses: actions/checkout@v4

      - name: Redirect temp directories to workspace for automated cleanup
        run: |
          $env:TEMP = "$env:GITHUB_WORKSPACE\temp"
          $env:TMP = "$env:GITHUB_WORKSPACE\temp"

      - name: Download built wheels
        uses: actions/download-artifact@v3
        with:
          name: "onnx-cpu-win-${{ matrix.wheel-arch }}-wheel"
          path: "downloads"

      - uses: ./.github/actions/setup-uv-env
        with:
          ENV_NAME: "onnx-cpu"
          VER_PYTHON: "${{ matrix.python-version }}"

      - name: Install AIMET-ONNX wheel
        run: |

          # Activate uv environment
          .\onnx-cpu\Scripts\Activate.ps1

          python -m ensurepip --upgrade
          python -m pip install uv

          # Install aimet-onnx
          $wheel = Get-ChildItem -Path downloads -Filter "aimet_onnx*.whl" | Select-Object -First 1 -ExpandProperty FullName
          python -m uv pip install "$wheel[test]" --extra-index-url="https://download.pytorch.org/whl/cpu" --index-strategy unsafe-best-match --native-tls

      - name: Run Unit tests
        if: inputs.run_unit_tests
        run: |

          # Activate uv environment
          .\onnx-cpu\Scripts\Activate.ps1

          # Run tests
          $pytest_args = "not cuda"
          Invoke-Expression "pytest -m `"$pytest_args`" -n 8 .\\ModelOptimizations\\DlQuantization\\test"
          Invoke-Expression "pytest -m `"$pytest_args`" -n 8 .\\TrainingExtensions\\common\\test\\python"
          # TODO: #6211 Move torch to onnx tests out of unit tests
          Invoke-Expression "pytest -m `"$pytest_args`" -n 8 .\\TrainingExtensions\\onnx\\test\\python --ignore .\\TrainingExtensions\\onnx\\test\\python\\test_torch_to_onnx.py"

      - name: Run Acceptance tests
        if: inputs.run_acceptance_tests
        run: |

          # Activate uv environment
          .\onnx-cpu\Scripts\Activate.ps1

          # Run tests
          $pytest_args = "not cuda"
          Invoke-Expression "pytest -m `"$pytest_args`" .\\NightlyTests\\onnx -n 8"

